spring.application.name=merogunaso
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=merogunasodb
server.address=0.0.0.0
server.port=${PORT:8080}
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# JWT Configuration
jwt.secret=cvT3T1rR3j7OpGp0QlJ7LwiKOEdP7gICBBxYWhrGVx8=
jwt.expiration=86400000

